"""
One-click demo fixtures.

These are illustrative sample cases. The receipt and visual-evidence blocks are
hand-written sample data (not live Textract / Bedrock output) so judges can run the
engine with zero setup. Real uploads go through POST /api/intake.
"""

DEMO_FIXTURES = {
    "case1_apple_iphone14plus": {
        "case_id": "demo_apple_iphone14plus",
        "product_name": "Apple iPhone 14 Plus (128GB Midnight)",
        "product_brand": "Apple",
        "product_model": "iPhone 14 Plus",
        "purchase_date": "2023-11-24",
        "failure_date": "2026-08-30",
        "purchase_country": "US",
        "retailer": "Best Buy",
        "payment_method": "Debit Card",
        "original_warranty_years": 1.0,
        "defect_description": "Rear camera shows a black screen with no preview in the Camera app. Front camera still works.",
        "already_paid_for_repair": False,
        "receipt_data": {
            "store_name": "Best Buy #1024",
            "purchase_date": "2023-11-24",
            "item_description": "Apple iPhone 14 Plus 128GB Midnight",
            "total_amount": 799.99,
            "currency": "USD",
            "payment_type": "DEBIT",
        },
        "visual_evidence": {
            "anomaly_detected": True,
            "visible_physical_damage": False,
            "physical_damage_severity": "none",
            "symptom_category": "rear_camera",
            "visual_observations": [
                "Back glass and rear camera lens covers intact with no visible cracks.",
                "Camera app open on rear camera shows a fully black preview.",
                "No visible signs of impact or liquid damage.",
            ],
        },
    },
    "case2_visa_infinite_sony": {
        "case_id": "demo_visa_infinite_sony",
        "product_name": "Sony WH-1000XM5 Wireless Noise-Cancelling Headphones",
        "product_brand": "Sony",
        "product_model": "WH-1000XM5",
        "purchase_date": "2025-03-14",
        "failure_date": "2026-09-05",
        "purchase_country": "US",
        "retailer": "Amazon.com",
        "payment_method": "Visa Infinite",
        "original_warranty_years": 1.0,
        "defect_description": "Left ear cup hinge cracked during normal adjustment; no drop or impact.",
        "receipt_data": {
            "store_name": "Amazon.com Services LLC",
            "purchase_date": "2025-03-14",
            "item_description": "Sony WH-1000XM5 Wireless Noise Canceling Headphones Black",
            "total_amount": 399.99,
            "currency": "USD",
            "payment_type": "VISA INFINITE (Ending 4092)",
        },
        "visual_evidence": {
            "anomaly_detected": True,
            "visible_physical_damage": True,
            "physical_damage_severity": "cosmetic",
            "symptom_category": "mechanical_hinge",
            "visual_observations": [
                "Fracture along the left ear cup hinge.",
                "Ear cushions and headband show normal light wear.",
                "No visible crush or impact marks.",
            ],
        },
    },
    "case3_uk_samsung_tv": {
        "case_id": "demo_uk_samsung_tv",
        "product_name": "Samsung 55-inch 4K HDR Smart TV",
        "product_brand": "Samsung",
        "product_model": "UE55CU7100KXXU",
        "purchase_date": "2023-07-20",
        "failure_date": "2026-08-22",
        "purchase_country": "GB",
        "retailer": "Currys",
        "payment_method": "Mastercard Debit",
        "original_warranty_years": 1.0,
        "defect_description": "Horizontal black lines and backlight flicker across the bottom third of the panel.",
        "receipt_data": {
            "store_name": "Currys Group Ltd",
            "purchase_date": "2023-07-20",
            "item_description": "SAMSUNG UE55CU7100KXXU 55\" Smart 4K Ultra HD HDR LED TV",
            "total_amount": 479.00,
            "currency": "GBP",
            "payment_type": "MASTERCARD DEBIT",
        },
        "visual_evidence": {
            "anomaly_detected": True,
            "visible_physical_damage": False,
            "physical_damage_severity": "none",
            "symptom_category": "display_panel",
            "visual_observations": [
                "Screen surface uncracked.",
                "Horizontal dark lines visible across the lower part of the panel.",
                "Artifact appears on the TV's own menus, not only on one input.",
            ],
        },
    },
    "case4_unknown_unsupported": {
        "case_id": "demo_unknown_unsupported",
        "product_name": "RetroPro Stainless Steel Espresso Machine",
        "product_brand": "RetroPro",
        "product_model": "EM-200",
        "purchase_date": "2023-01-10",
        "failure_date": "2026-04-12",
        "purchase_country": "US",
        "retailer": "HomeStyle Goods",
        "payment_method": "Cash",
        "original_warranty_years": 1.0,
        "defect_description": "Pump no longer reaches extraction pressure.",
        "receipt_data": {
            "store_name": "HomeStyle Goods #401",
            "purchase_date": "2023-01-10",
            "item_description": "RetroPro EM-200 Pump Espresso Maker",
            "total_amount": 189.95,
            "currency": "USD",
            "payment_type": "CASH",
        },
        "visual_evidence": {
            "anomaly_detected": False,
            "visible_physical_damage": False,
            "physical_damage_severity": "none",
            "symptom_category": "internal_pump",
            "visual_observations": ["Enclosure exterior clean; no external damage or leaks."],
        },
    },
}
